- name: be sure install requirement packages
  yum: name={{ item }} state=installed
  with_items:
    - httpd
    - httpd-tools

- name: be sure virtualhost configuration exist
  copy: src="etc/httpd/conf.d/virtualhost.conf" dest="/etc/httpd/conf.d/virtualhost.conf"

- name: be sure welcome.conf does not exist
  file: path="/etc/httpd/conf.d/welcome.conf" state=absent
